### PR TITLE
EU Coordinates

### PR DESCRIPTION
**Pull request by rscircus**
Add's the EU coordinates to map the venues on.

### CODE REVIEW

**Comment by fatiherikli** [comment]
hello @rscircus, thanks for your contribution! why did you close the PR?

**Comment by rscircus** [comment]
Hey Fatih,

first of all: Thanks for the awesome work and that you open sourced it.

I added it mistakenly to your repo, but it doesn't matter as I wanted to reach out in the afternoon either. We forked it for euvsvirus.org this weekend. You wanna join? :-)

We discussed to ask you already in the slack, as none of us is a React guy. :-)

Best,

Roland

**Comment by rscircus** [comment]
We mentioned you already in our idea proposal:

https://devpost.com/software/political-policies-effect-on-covid-19-spread-inside-the-eu-uamhdv

yesterday. :-)

**Comment by fatiherikli** [comment]
Thanks a lot, @rscircus! I'm already on the EUvsVirus slack channel and I would love to join. I'll ping you there :)

**Pull request closed without merging**
